#!/bin/bash

gen_output="output"

if [ -d $gen_output ]; then
	rm -rf $gen_output
fi

CLASSPATH=${CLASSPATH}:`dirname $0`/../lib/${artifactId}-${version}.jar:`dirname $0`/../lib/bonita-server-${bos.Version}.jar

. wsdl2java -d $gen_output -compile -frontend bonita $1

if [ -d $gen_output ]; then
	cd $gen_output
	jar cf bonita-ws-connectors.jar *
	cd ..
	echo -e "\nGenerated Bonita connector in directory '$gen_output'\n"
fi